#!/bin/bash
export DISPLAY=:0

#TODO:
# - figure out why and when printer is spitting one blank file.
#
# -o page-set=even makes the printer spit one blank before printing
# looks like it has something to do with the duplex printing instructions
#Uncomment this to log to /var/log/cups/error_log
LogFile=/var/log/cups/error_log
LOG() {
    echo "$@" >> $LogFile
}
# Output "Device Discovery" information on stdout:
if test "$#" = "0"
then
  echo 'direct duplex-print "Unknown" "(!) Manual_duplexer unit for linux. (!)"'
  exit 0
fi

#GET PRINTER AND USER FROM URI
#clip spaces
URI=${DEVICE_URI%% *}
# Extract the printer from the uri to which the job schould be sent from the URI.
# Clip the URI scheme (anything up to the first ':' character) and
# clip anything after the first '?' character
USE_PRINTER=${URI#*:}
USE_PRINTER=${USE_PRINTER%%\?*}

# Command line arguments
job="$1"
user="$2"
title="$3"
numcopies="$4"
options="$5"
filename="/var/spool/cups/duplex/$job.duplex"

LOG ---
LOG $(date) --- Starting duplexer job
LOG $(date) --- Script called by $user and runs as $(whoami) with logname $(logname)

lp_args=
for opt in $options
do
	lp_args="$lp_args -o $opt"
done

#test if file exists
while [ ! -f "$filename" ]
do
  sleep 1
done

page_count=$(pdfinfo "$filename" | grep Pages | awk '{print $2}')
LOG $(date) --- "page count: $page_count"

#if only one page, just send the printing command
if [ $(( $page_count )) -eq 1 ]; then
	LOG $(date) --- printing ONE page
	lp -s -d $USE_PRINTER -n "$numcopies" $lp_args -o collate=true -o orientation-requested=6 -t "$title"-even "$filename"

#if more than one pages, print odd pages first and show user interface
elif [ $(( $page_count )) -gt 1 ]; then
	LOG $(date) --- more than one page was sent. printing odd pages
	lp -s -d $USE_PRINTER -n "$numcopies" $lp_args -o page-set=odd -o collate=true -o outputorder=normal \
		-o orientation-requested=6 -t "$title"-odd "$filename"

	#show user interface
	LOG $(date) --- Will Show user interface.

  if [ -z "$DISPLAY" ]; then
    LOG $(date) --- "No display found trying to set one" 
    #export display for zenity to use
    export DISPLAY=$(who -su | grep $user | awk '$2 ~ /:[0-9.]*/{print $2}')
	fi

	LOG $(date) --- Running on display number $DISPLAY
  xhost +SI:localuser:cups #!TAKE A LOOK, THIS IS HACKY FOR ME but it does the job.
	sudo --user=$user \
	zenity --question --title="$title" \
        --text="<big><b>Flip and reinsert the entire paper stack when printing has finished,\n\n then press Procceed.</b></big>\n\n\n\n
         Finding my work usefull?               <a href='https://www.paypal.com/paypalme2/nanonetK3'>Click here to buy me a cofee.</a>" \
        --icon-name="document-print" \
        --window-icon "/usr/share/manual_duplex_linux/printer.png" \
        --ok-label="Proceed" --cancel-label="Cancel" \
        --display=$DISPLAY \
        --width=$(echo $(sudo -u $user xdpyinfo -display $DISPLAY | grep dimensions | sed -r 's/^[^0-9]*([0-9]+).*$/\1/') / 3 | bc) 2>>$LogFile; last_command_return=$?

    LOG $(date) --- User interface has been shown.
	if (($last_command_return==0)); then
		LOG $(date) --- printing even pages
		lp -s -d $USE_PRINTER -n "$numcopies" $lp_args -o page-set=even -o collate=true -o outputorder=normal \
			-o orientation-requested=6 -t "$title"-even "$filename"
  xhost -SI:localuser:cups
  LOG $(date) --- printing done - removed xhost
# UNCOMMENT IF CUPS-FILTERS VERSION IS BELOW 1.0.55
# Also SET your main printer as default printer
# SEE https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1340435
#        LOG $(date) --- PRINT ONE BLANK if needed
#        if [ `expr $page_count % 2` == 0 ]; then
#		LOG $(date) --- No need for blanks - pages are even
#        else
#		LOG $(date) --- spitting a blank - pages are odd
#		echo |  lp -s -t "$filename"-blank
#        fi


    else
        LOG $(date) --- User aborted print job
        rm "$filename"
        exit 0
    fi
fi

rm "$filename"
exit 0
